---
- name: Load OS-specific variables
  include_vars: "{{lookup('first_found', params)}}"
  vars:
    params:
      files:
        - "{{ansible_distribution}}.yml"
        - "{{ansible_os_family}}.yml"
        - default.yml
      paths:
        - "vars"

- name: Install Icecast
  package:
    name: "{{ icecast_package }}"
    state: present

- name: Install Icecast configuration file
  template:
    src: icecast.xml.j2
    dest: "{{ icecast_config_file }}"
    owner: "{{ icecast_user }}"
    group: "{{ icecast_group }}"
    mode: 0640
  notify:
    - reload icecast

- name: Enable Icecast service
  service:
    name: "{{ icecast_service }}"
    enabled: yes
